/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as CatalogoIdRouteImport } from './routes/catalogo.$id'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalCategoriasRouteImport } from './routes/portal.categorias'
import { Route as PortalConfiguracoesRouteImport } from './routes/portal.configuracoes'
import { Route as PortalDashboardRouteImport } from './routes/portal.dashboard'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as PortalManutencoesRouteImport } from './routes/portal.manutencoes'
import { Route as PortalRelatoriosRouteImport } from './routes/portal.relatorios'
import { Route as PortalAlugueisIndexRouteImport } from './routes/portal.alugueis.index'
import { Route as PortalAlugueisIdRouteImport } from './routes/portal.alugueis.$id'
import { Route as PortalAlugueisNovoRouteImport } from './routes/portal.alugueis.novo'
import { Route as PortalClientesIndexRouteImport } from './routes/portal.clientes.index'
import { Route as PortalClientesIdRouteImport } from './routes/portal.clientes.$id'
import { Route as PortalEquipamentosIndexRouteImport } from './routes/portal.equipamentos.index'
import { Route as PortalEquipamentosIdRouteImport } from './routes/portal.equipamentos.$id'
import { Route as PortalOrcamentosIndexRouteImport } from './routes/portal.orcamentos.index'
import { Route as PortalOrcamentosIdRouteImport } from './routes/portal.orcamentos.$id'
import { Route as PortalOrcamentosNovoRouteImport } from './routes/portal.orcamentos.novo'
import { Route as PortalAlugueisIdTermoRouteImport } from './routes/portal.alugueis.$id.termo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoIdRoute = CatalogoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CatalogoRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCategoriasRoute = PortalCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => PortalRoute,
} as any)
const PortalConfiguracoesRoute = PortalConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const PortalManutencoesRoute = PortalManutencoesRouteImport.update({
  id: '/manutencoes',
  path: '/manutencoes',
  getParentRoute: () => PortalRoute,
} as any)
const PortalRelatoriosRoute = PortalRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAlugueisIndexRoute = PortalAlugueisIndexRouteImport.update({
  id: '/alugueis/',
  path: '/alugueis/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAlugueisIdRoute = PortalAlugueisIdRouteImport.update({
  id: '/alugueis/$id',
  path: '/alugueis/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAlugueisNovoRoute = PortalAlugueisNovoRouteImport.update({
  id: '/alugueis/novo',
  path: '/alugueis/novo',
  getParentRoute: () => PortalRoute,
} as any)
const PortalClientesIndexRoute = PortalClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalClientesIdRoute = PortalClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEquipamentosIndexRoute = PortalEquipamentosIndexRouteImport.update({
  id: '/equipamentos/',
  path: '/equipamentos/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEquipamentosIdRoute = PortalEquipamentosIdRouteImport.update({
  id: '/equipamentos/$id',
  path: '/equipamentos/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOrcamentosIndexRoute = PortalOrcamentosIndexRouteImport.update({
  id: '/orcamentos/',
  path: '/orcamentos/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOrcamentosIdRoute = PortalOrcamentosIdRouteImport.update({
  id: '/orcamentos/$id',
  path: '/orcamentos/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOrcamentosNovoRoute = PortalOrcamentosNovoRouteImport.update({
  id: '/orcamentos/novo',
  path: '/orcamentos/novo',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAlugueisIdTermoRoute = PortalAlugueisIdTermoRouteImport.update({
  id: '/termo',
  path: '/termo',
  getParentRoute: () => PortalAlugueisIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/catalogo/$id': typeof CatalogoIdRoute
  '/portal/categorias': typeof PortalCategoriasRoute
  '/portal/configuracoes': typeof PortalConfiguracoesRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/manutencoes': typeof PortalManutencoesRoute
  '/portal/relatorios': typeof PortalRelatoriosRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/alugueis/$id': typeof PortalAlugueisIdRouteWithChildren
  '/portal/alugueis/novo': typeof PortalAlugueisNovoRoute
  '/portal/clientes/$id': typeof PortalClientesIdRoute
  '/portal/equipamentos/$id': typeof PortalEquipamentosIdRoute
  '/portal/orcamentos/$id': typeof PortalOrcamentosIdRoute
  '/portal/orcamentos/novo': typeof PortalOrcamentosNovoRoute
  '/portal/alugueis/': typeof PortalAlugueisIndexRoute
  '/portal/clientes/': typeof PortalClientesIndexRoute
  '/portal/equipamentos/': typeof PortalEquipamentosIndexRoute
  '/portal/orcamentos/': typeof PortalOrcamentosIndexRoute
  '/portal/alugueis/$id/termo': typeof PortalAlugueisIdTermoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/catalogo/$id': typeof CatalogoIdRoute
  '/portal/categorias': typeof PortalCategoriasRoute
  '/portal/configuracoes': typeof PortalConfiguracoesRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/manutencoes': typeof PortalManutencoesRoute
  '/portal/relatorios': typeof PortalRelatoriosRoute
  '/portal': typeof PortalIndexRoute
  '/portal/alugueis/$id': typeof PortalAlugueisIdRouteWithChildren
  '/portal/alugueis/novo': typeof PortalAlugueisNovoRoute
  '/portal/clientes/$id': typeof PortalClientesIdRoute
  '/portal/equipamentos/$id': typeof PortalEquipamentosIdRoute
  '/portal/orcamentos/$id': typeof PortalOrcamentosIdRoute
  '/portal/orcamentos/novo': typeof PortalOrcamentosNovoRoute
  '/portal/alugueis': typeof PortalAlugueisIndexRoute
  '/portal/clientes': typeof PortalClientesIndexRoute
  '/portal/equipamentos': typeof PortalEquipamentosIndexRoute
  '/portal/orcamentos': typeof PortalOrcamentosIndexRoute
  '/portal/alugueis/$id/termo': typeof PortalAlugueisIdTermoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/catalogo/$id': typeof CatalogoIdRoute
  '/portal/categorias': typeof PortalCategoriasRoute
  '/portal/configuracoes': typeof PortalConfiguracoesRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/manutencoes': typeof PortalManutencoesRoute
  '/portal/relatorios': typeof PortalRelatoriosRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/alugueis/$id': typeof PortalAlugueisIdRouteWithChildren
  '/portal/alugueis/novo': typeof PortalAlugueisNovoRoute
  '/portal/clientes/$id': typeof PortalClientesIdRoute
  '/portal/equipamentos/$id': typeof PortalEquipamentosIdRoute
  '/portal/orcamentos/$id': typeof PortalOrcamentosIdRoute
  '/portal/orcamentos/novo': typeof PortalOrcamentosNovoRoute
  '/portal/alugueis/': typeof PortalAlugueisIndexRoute
  '/portal/clientes/': typeof PortalClientesIndexRoute
  '/portal/equipamentos/': typeof PortalEquipamentosIndexRoute
  '/portal/orcamentos/': typeof PortalOrcamentosIndexRoute
  '/portal/alugueis/$id/termo': typeof PortalAlugueisIdTermoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogo'
    | '/portal'
    | '/catalogo/$id'
    | '/portal/categorias'
    | '/portal/configuracoes'
    | '/portal/dashboard'
    | '/portal/login'
    | '/portal/manutencoes'
    | '/portal/relatorios'
    | '/portal/'
    | '/portal/alugueis/$id'
    | '/portal/alugueis/novo'
    | '/portal/clientes/$id'
    | '/portal/equipamentos/$id'
    | '/portal/orcamentos/$id'
    | '/portal/orcamentos/novo'
    | '/portal/alugueis/'
    | '/portal/clientes/'
    | '/portal/equipamentos/'
    | '/portal/orcamentos/'
    | '/portal/alugueis/$id/termo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/catalogo/$id'
    | '/portal/categorias'
    | '/portal/configuracoes'
    | '/portal/dashboard'
    | '/portal/login'
    | '/portal/manutencoes'
    | '/portal/relatorios'
    | '/portal'
    | '/portal/alugueis/$id'
    | '/portal/alugueis/novo'
    | '/portal/clientes/$id'
    | '/portal/equipamentos/$id'
    | '/portal/orcamentos/$id'
    | '/portal/orcamentos/novo'
    | '/portal/alugueis'
    | '/portal/clientes'
    | '/portal/equipamentos'
    | '/portal/orcamentos'
    | '/portal/alugueis/$id/termo'
  id:
    | '__root__'
    | '/'
    | '/catalogo'
    | '/portal'
    | '/catalogo/$id'
    | '/portal/categorias'
    | '/portal/configuracoes'
    | '/portal/dashboard'
    | '/portal/login'
    | '/portal/manutencoes'
    | '/portal/relatorios'
    | '/portal/'
    | '/portal/alugueis/$id'
    | '/portal/alugueis/novo'
    | '/portal/clientes/$id'
    | '/portal/equipamentos/$id'
    | '/portal/orcamentos/$id'
    | '/portal/orcamentos/novo'
    | '/portal/alugueis/'
    | '/portal/clientes/'
    | '/portal/equipamentos/'
    | '/portal/orcamentos/'
    | '/portal/alugueis/$id/termo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/$id': {
      id: '/catalogo/$id'
      path: '/$id'
      fullPath: '/catalogo/$id'
      preLoaderRoute: typeof CatalogoIdRouteImport
      parentRoute: typeof CatalogoRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/categorias': {
      id: '/portal/categorias'
      path: '/categorias'
      fullPath: '/portal/categorias'
      preLoaderRoute: typeof PortalCategoriasRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/configuracoes': {
      id: '/portal/configuracoes'
      path: '/configuracoes'
      fullPath: '/portal/configuracoes'
      preLoaderRoute: typeof PortalConfiguracoesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/manutencoes': {
      id: '/portal/manutencoes'
      path: '/manutencoes'
      fullPath: '/portal/manutencoes'
      preLoaderRoute: typeof PortalManutencoesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/relatorios': {
      id: '/portal/relatorios'
      path: '/relatorios'
      fullPath: '/portal/relatorios'
      preLoaderRoute: typeof PortalRelatoriosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/alugueis/': {
      id: '/portal/alugueis/'
      path: '/alugueis'
      fullPath: '/portal/alugueis/'
      preLoaderRoute: typeof PortalAlugueisIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/alugueis/$id': {
      id: '/portal/alugueis/$id'
      path: '/alugueis/$id'
      fullPath: '/portal/alugueis/$id'
      preLoaderRoute: typeof PortalAlugueisIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/alugueis/novo': {
      id: '/portal/alugueis/novo'
      path: '/alugueis/novo'
      fullPath: '/portal/alugueis/novo'
      preLoaderRoute: typeof PortalAlugueisNovoRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/clientes/': {
      id: '/portal/clientes/'
      path: '/clientes'
      fullPath: '/portal/clientes/'
      preLoaderRoute: typeof PortalClientesIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/clientes/$id': {
      id: '/portal/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/portal/clientes/$id'
      preLoaderRoute: typeof PortalClientesIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/equipamentos/': {
      id: '/portal/equipamentos/'
      path: '/equipamentos'
      fullPath: '/portal/equipamentos/'
      preLoaderRoute: typeof PortalEquipamentosIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/equipamentos/$id': {
      id: '/portal/equipamentos/$id'
      path: '/equipamentos/$id'
      fullPath: '/portal/equipamentos/$id'
      preLoaderRoute: typeof PortalEquipamentosIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/orcamentos/': {
      id: '/portal/orcamentos/'
      path: '/orcamentos'
      fullPath: '/portal/orcamentos/'
      preLoaderRoute: typeof PortalOrcamentosIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/orcamentos/$id': {
      id: '/portal/orcamentos/$id'
      path: '/orcamentos/$id'
      fullPath: '/portal/orcamentos/$id'
      preLoaderRoute: typeof PortalOrcamentosIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/orcamentos/novo': {
      id: '/portal/orcamentos/novo'
      path: '/orcamentos/novo'
      fullPath: '/portal/orcamentos/novo'
      preLoaderRoute: typeof PortalOrcamentosNovoRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/alugueis/$id/termo': {
      id: '/portal/alugueis/$id/termo'
      path: '/termo'
      fullPath: '/portal/alugueis/$id/termo'
      preLoaderRoute: typeof PortalAlugueisIdTermoRouteImport
      parentRoute: typeof PortalAlugueisIdRoute
    }
  }
}

interface CatalogoRouteChildren {
  CatalogoIdRoute: typeof CatalogoIdRoute
}

const CatalogoRouteChildren: CatalogoRouteChildren = {
  CatalogoIdRoute: CatalogoIdRoute,
}

const CatalogoRouteWithChildren = CatalogoRoute._addFileChildren(
  CatalogoRouteChildren,
)

interface PortalAlugueisIdRouteChildren {
  PortalAlugueisIdTermoRoute: typeof PortalAlugueisIdTermoRoute
}

const PortalAlugueisIdRouteChildren: PortalAlugueisIdRouteChildren = {
  PortalAlugueisIdTermoRoute: PortalAlugueisIdTermoRoute,
}

const PortalAlugueisIdRouteWithChildren =
  PortalAlugueisIdRoute._addFileChildren(PortalAlugueisIdRouteChildren)

interface PortalRouteChildren {
  PortalCategoriasRoute: typeof PortalCategoriasRoute
  PortalConfiguracoesRoute: typeof PortalConfiguracoesRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalManutencoesRoute: typeof PortalManutencoesRoute
  PortalRelatoriosRoute: typeof PortalRelatoriosRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalAlugueisIdRoute: typeof PortalAlugueisIdRouteWithChildren
  PortalAlugueisNovoRoute: typeof PortalAlugueisNovoRoute
  PortalClientesIdRoute: typeof PortalClientesIdRoute
  PortalEquipamentosIdRoute: typeof PortalEquipamentosIdRoute
  PortalOrcamentosIdRoute: typeof PortalOrcamentosIdRoute
  PortalOrcamentosNovoRoute: typeof PortalOrcamentosNovoRoute
  PortalAlugueisIndexRoute: typeof PortalAlugueisIndexRoute
  PortalClientesIndexRoute: typeof PortalClientesIndexRoute
  PortalEquipamentosIndexRoute: typeof PortalEquipamentosIndexRoute
  PortalOrcamentosIndexRoute: typeof PortalOrcamentosIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalCategoriasRoute: PortalCategoriasRoute,
  PortalConfiguracoesRoute: PortalConfiguracoesRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalManutencoesRoute: PortalManutencoesRoute,
  PortalRelatoriosRoute: PortalRelatoriosRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalAlugueisIdRoute: PortalAlugueisIdRouteWithChildren,
  PortalAlugueisNovoRoute: PortalAlugueisNovoRoute,
  PortalClientesIdRoute: PortalClientesIdRoute,
  PortalEquipamentosIdRoute: PortalEquipamentosIdRoute,
  PortalOrcamentosIdRoute: PortalOrcamentosIdRoute,
  PortalOrcamentosNovoRoute: PortalOrcamentosNovoRoute,
  PortalAlugueisIndexRoute: PortalAlugueisIndexRoute,
  PortalClientesIndexRoute: PortalClientesIndexRoute,
  PortalEquipamentosIndexRoute: PortalEquipamentosIndexRoute,
  PortalOrcamentosIndexRoute: PortalOrcamentosIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
