// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttskmskjxnftmfafyrru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0c2ttc2tqeG5mdG1mYWZ5cnJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUxNjUxMjYsImV4cCI6MjEwMDc0MTEyNn0.9OBbt3VBeVei-HKIGU9l6oQwvDRc6t_QrOa_3TXjp8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});